microservice-chart:
  namespace: "migration-toolkit"
  nameOverride: ""
  fullnameOverride: ""

  startupProbe:
    create: true
    httpGet:
      path: /actuator/health/liveness
      port: 8080
    initialDelaySeconds: 30
    failureThreshold: 15
    periodSeconds: 10

  livenessProbe:
    httpGet:
      path: /actuator/health/liveness
      port: 8080
    failureThreshold: 15
    periodSeconds: 10

  readinessProbe:
    httpGet:
      path: /actuator/health/readiness
      port: 8080
    initialDelaySeconds: 5
    failureThreshold: 15
    periodSeconds: 10

  deployment:
    create: true

  service:
    create: true
    type: ClusterIP
    port: 8080

  ingress:
    create: true
    path: /mypayp4paextractor/(.*)

  serviceAccount:
    create: false
    annotations: {}
    name: ""

  podAnnotations: {}

  podSecurityContext:
    seccompProfile:
      type: RuntimeDefault

  securityContext:
    allowPrivilegeEscalation: false
    runAsNonRoot: true
    runAsUser: 65534
    runAsGroup: 65534

  # externalConfigMapFiles:
  #   create: true
  #   configMaps:
  #     - name: appinsights-config
  #       key: applicationinsights.json

  envConfig:
    APPLICATIONINSIGHTS_ROLE_NAME: "mypay-p4pa-extractor"
    APPLICATIONINSIGHTS_INSTRUMENTATION_LOGGING_LEVEL: "OFF"
    APPLICATIONINSIGHTS_INSTRUMENTATION_MICROMETER_ENABLED: "false"
    APPLICATIONINSIGHTS_PREVIEW_PROFILER_ENABLED: "false"
    ENABLE_AUDIT_APPENDER: "TRUE"

    STORAGE_PATH: "/tmp/data/extractions" # TODO should it be persistent? should it be shared?

    MP4_DB_NAME: "mypay_migration_toolkit"
    FESP_DB_NAME: "fesp_migration_toolkit"
    MPV4_DB_NAME: "mypivot_migration_toolkit"

    MYPIVOT_ENABLED: "true"

    MYDICTIONARY_BASE_URL: "http://p4pa-mocks-microservice-chart.payhub.svc.cluster.local:8080/mydictionary"
    MYDICT_API_KEY: "MYDICTIONARY_DUMMY_API_KEY"

  envSecret:
    # APPLICATIONINSIGHTS_CONNECTION_STRING: appinsights-connection-string
    MP4_DB_HOST: db-host
    MP4_DB_USER: db-migration-toolkit-login-username
    MP4_DB_PASSWORD: db-migration-toolkit-login-password

    FESP_DB_HOST: db-host
    FESP_DB_USER: db-migration-toolkit-login-username
    FESP_DB_PASSWORD: db-migration-toolkit-login-password

    MPV4_DB_HOST: db-host
    MPV4_DB_USER: db-migration-toolkit-login-username
    MPV4_DB_PASSWORD: db-migration-toolkit-login-password

    CLIENT_ID: mypay-p4pa-toolkit-client-id
    CLIENT_SECRET: mypay-p4pa-toolkit-client-secret

  # nodeSelector: {}

  tolerations:
    - key: "puOnly"
      operator: "Equal"
      value: "true"
      effect: "NoSchedule"

  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: domain
                operator: In
                values:
                  - pu
